### ISSUE TITLE
Question if a particular description (red colored) is correct: `Resolve import naming collision`

### ISSUE THREAD

**Issue by fgeorgatos** [quantifiedcode/quantifiedcode#2]
Not sure if this is the right place to open the case, but here we go:

The warning is about `Resolve import naming collision` but we don't see the obvious fix!
https://www.quantifiedcode.com/app/project/gh:fgeorgatos:qtop/diff/1656352aafb75800c27878ad9879354411e9219b/4cd07a18e5c233f1e6fb5980d6ff178eeb238b56/issues?groups=code_patterns%3AkJ13jArn%3Af0%3Ao0

Could you review and let us know, if either quantifiedcode or qtop needs a fix?! tia, F.

**Comment by adewes** [comment]
Oh sorry if the error message is not very clear, QC just complains that you imported `os` (and `sys`) more than once, you can solve this by removing the second, unnecessary import. Hope this helps, if you think this resolves the issue please feel free to close it, otherwise just let us know as well. Thanks!
